### ISSUE TITLE
Not recognized on Windows 10 May 2019 update (1903)

### ISSUE THREAD

**Issue by mdvdhurk** [yo1995/Daily_GUI_Tools#3]
Hi,

After upgrading from W10 1809 I can't use the tool for the LG UltraFine (5k) anymore. The gui version tells me: error check your connection, while the commandline version says: 
```
PS C:\Program Files (x86)\LG-Ultrafine-Brightness> .\brightness-tool.exe
libusb: error [init_device] device '\\.\USB#VID_043E&PID_9A40&MI_01#D&25046796&0&0001' is no longer connected!
libusb: error [init_device] device '\\.\USB#VID_046D&PID_C52B&MI_02#6&26DBD308&0&0002' is no longer connected!
libusb: warning [init_device] could not get node connection information for device '\\.\USB#VID_043E&PID_9A40&MI_02#D&25046796&0&0002': [87] The parameter is incorrect.
Failed to claim interface 1. Error: -12
Error: LIBUSB_ERROR_NOT_SUPPORTED
```

The display is active, the only one connected and works fine except for the brightness adjustment. Could you help out? Thanks!

_(btw: I have also tried the tool you mentioned in the references; this one reports: Unable to set a feature report)_

**Comment by yo1995** [comment]
> Hi,
> 
> After upgrading from W10 1809 I can't use the tool for the LG UltraFine (5k) anymore. The gui version tells me: error check your connection, while the commandline version says:
> 
> ```
> PS C:\Program Files (x86)\LG-Ultrafine-Brightness> .\brightness-tool.exe
> libusb: error [init_device] device '\\.\USB#VID_043E&PID_9A40&MI_01#D&25046796&0&0001' is no longer connected!
> libusb: error [init_device] device '\\.\USB#VID_046D&PID_C52B&MI_02#6&26DBD308&0&0002' is no longer connected!
> libusb: warning [init_device] could not get node connection information for device '\\.\USB#VID_043E&PID_9A40&MI_02#D&25046796&0&0002': [87] The parameter is incorrect.
> Failed to claim interface 1. Error: -12
> Error: LIBUSB_ERROR_NOT_SUPPORTED
> ```
> 
> The display is active, the only one connected and works fine except for the brightness adjustment. Could you help out? Thanks!
> 
> _(btw: I have also tried the tool you mentioned in the references; this one reports: Unable to set a feature report)_

it seems to be related with a compatibility issue with libusb. I'll check that

**Comment by yo1995** [comment]
> Hi,
> 
> After upgrading from W10 1809 I can't use the tool for the LG UltraFine (5k) anymore. The gui version tells me: error check your connection, while the commandline version says:
> 
> ```
> PS C:\Program Files (x86)\LG-Ultrafine-Brightness> .\brightness-tool.exe
> libusb: error [init_device] device '\\.\USB#VID_043E&PID_9A40&MI_01#D&25046796&0&0001' is no longer connected!
> libusb: error [init_device] device '\\.\USB#VID_046D&PID_C52B&MI_02#6&26DBD308&0&0002' is no longer connected!
> libusb: warning [init_device] could not get node connection information for device '\\.\USB#VID_043E&PID_9A40&MI_02#D&25046796&0&0002': [87] The parameter is incorrect.
> Failed to claim interface 1. Error: -12
> Error: LIBUSB_ERROR_NOT_SUPPORTED
> ```
> 
> The display is active, the only one connected and works fine except for the brightness adjustment. Could you help out? Thanks!
> 
> _(btw: I have also tried the tool you mentioned in the references; this one reports: Unable to set a feature report)_

Hi,

Would you please download both files and try the latest version at https://github.com/yo1995/Daily_GUI_Tools/tree/master/Tool_LG-Ultrafine-brightness/CLR_GUI/Released

Since I have not updated my Windows OS yet, I cannot test it with the latest 1903. If the problem persists, I may need to further investigate after I upgrade sometime later this year.

**Comment by mdvdhurk** [comment]
Hi,
Thank you for your quick response and solution. I can confirm it works on
W10-1903 with an LG UltraFine 5k! Excellent!
Best regards, Mark

Op do 30 mei 2019 om 03:35 schreef cht <notifications@github.com>:
