### ISSUE TITLE
LG Ultrafine Brightness multi-monitor

### ISSUE THREAD

**Issue by quentez** [yo1995/Daily_GUI_Tools#8]
I've tried your GUI tool and it works perfectly 🙂 ! Only problem is I have two Ultrafines 4k connected to my Windows PC and the tool will only control one of the two. Do you know if it would be possible to update it to target all connected monitors?

(I haven't looked at the code yet, but might take a look this weekend to see if I can find a way to do this).

**Comment by yo1995** [comment]
oh! really nice to hear that!
Yes sure it should be possible, as I only deal with the first found monitor with the device id. I'll report in when I touch the code.

**Comment by yo1995** [comment]
...and it would be great if you edit & compile the code yourself, as I'll probably lose my office with LG5K soon, so no more real device validation...not sure when I can buy one myself 😢 

the code is a bit not well organized, as I was trying to develop a conf file feature, but haven't done due to recent activities...

**Comment by quentez** [comment]
@yo1995 Sorry to hear about the LG5K. It's a great monitor!

I've been playing around with it yesterday and replicated the code in C# without the need for a 3rd party library. I'm going to see how difficult it would be to ship that on the Windows Store for people to use more easily.

**Comment by quentez** [comment]
@yo1995 I've gotten carried away and ended up building a full GUI tool to control the brightness. Let me know if you'd like access to the beta 🙂 

https://www.reddit.com/r/bootcamp/comments/f67u1e/lg_ultrafine_brightness_control/

**Comment by yo1995** [comment]
@quentez Super nice and looks slick! Once you have the release version, please let me know so I can put a redirection to your version in the readme. 😃

**Comment by quentez** [comment]
@yo1995 The app is now live here: https://www.microsoft.com/en-us/p/lg-ultrafine-brightness/9n5mj2fq4gww

Let me know what you think 🙂 !

**Comment by ducsonnguyen** [comment]
Thank you so much for this @quentez (and @yo1995 for starting it and anyone else who contributed)! Just installed it from the MS Store and it allows my HP Elitebook to control the Ultrafine 5K’s brightness perfectly and conveniently. Left you a good review. Thanks again!

**Comment by quentez** [comment]
@duc1701 Glad I could help 🙂 ! 
I'm happy to hear it's working with the 5k version. I wasn't able to get my hands on one.

**Comment by yo1995** [comment]
@quentez Thanks for your help, and I've added a pointer to your MS Store version in the README!

As I've lost my access to the 5K, I hope your software can help even more users who find this repo! 😺
